### ISSUE TITLE
Extract Sensor Data input ( Ultrasonic or Proximity )

### ISSUE THREAD

**Issue by mayankofficial999** [IEEE-VIT/obstacle-avoider#1]
- This function aims to collect the data from obstacle detecting sensors that are used in the robot car.  
> Eg: Ultrasonic , IR ,IR Proximity .

**Comment by aayushkumr25** [comment]
Do i just have to serial print the input or something else too?

**Comment by mayankofficial999** [comment]
Nothing else is needed. Serial print of the incoming sensor data is enough.
(Wrapped inside a function)

**Comment by aayushkumr25** [comment]
ok i want to work on it can you please assign it to me

**Comment by himanshushah05** [comment]
@aayushkumr25, I have made you a contributor.
All the best.
