### ISSUE TITLE
Distance calculator

### ISSUE THREAD

**Issue by mayankofficial999** [IEEE-VIT/obstacle-avoider#2]
- This function will calculate the distance of obstacles (in cms) by taking the sensor data as input.

**Comment by deeppss** [comment]
Hello! Can I work on this issue? I have a small doubt regarding the issue mentioned here.  In the code, there is only one function for both reading the sensor data and calculating the distance.  But there are 2 separate issues allotted. Shall I store sensor data and calculate distance in the same function ```double calcDistance```

**Comment by iamanshulgit** [comment]
Hello, Can you please assign this task to me so I can contribute to this project? Thank you

**Comment by himanshushah05** [comment]
Hi @deeppss, it would be better to have 2 different functions. As it is possible that someone can use IR sensor to get sensor data, that's why we have 2 separate functions.
I have assigned you the issue. 
All the best.

**Comment by himanshushah05** [comment]
Hey guys, @deeppss and @iamanshulgit, you both can work on this issue and raise a PR.
