### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by mayankofficial999** [IEEE-VIT/obstacle-avoider#5]
- To detect and return a logic level depending on the presence of an obstacle in front of the vehicle.

**Comment by iamanshulgit** [comment]
Hello Mayank, I would like to work on this issue. If you assign me the task then I start the work on it?

**Comment by iamanshulgit** [comment]
Hello, If it is still open I would like to work on it. Can you please assign it to me? Thank you

**Comment by mayankofficial999** [comment]
Yes , @iamanshulgit you can work on this issue.
Assigned
